name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine # Usar directamente un contenedor con Node.js 20
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Verify Node version
        run: |
          node -v
          npm -v
          
      - name: Install dependencies
        run: npm ci
        working-directory: FcnoLimit
        
      - name: Configure environment variables
        run: |
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
          echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> .env
        working-directory: FcnoLimit
        
      - name: Build
        run: npm run build
        working-directory: FcnoLimit
      
      - name: Install specific version of firebase-tools
        run: npm install -g firebase-tools@13.0.2
      
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN" --project fcnolimit-app --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FCNOLIMIT }}
        working-directory: FcnoLimit